name: update deployment information

on:
  push:

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: configure aws
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: install aws cli
      run: |
        apt update -y && apt install -y rsync python python3-pip
        pip install awscli
    - name: upload version.json to s3
      run: |
        aws s3 sync ./version.json s3://${{ secrets.AWS_S3_BUCKET }}/gitea/version.json --no-progress